# t870_msgs/msg/Feedback.msg

# Message header
std_msgs/Header header

# Control mode (Manual / Auto)
bool manual_mode

# Emergency stop (ON / OFF)
bool emergency_stop

# Gear (Forward / Neutral / Backward)
uint8 GEAR_FORWARD  = 0
uint8 GEAR_NEUTRAL  = 1
uint8 GEAR_BACKWARD = 2
uint8 gear

# Vehicle speed (m/s)
float64 speed

# Steering angle (rad)
float64 steering

# Encoder count (-2^31 - 2^31)
int32 encoder_count

# Health check counter (0 - 255)
uint8 heartbeat